/**
 * Process Lead Netlify Function
 * Receives lead data from embedded calculators and emails it to the partner's
 * intake email via Resend API. Always BCCs the CaseValue team.
 */

const RESEND_API_URL = 'https://api.resend.com/emails';
const BCC_EMAIL = 'info@leadvera.com';
const FROM_EMAIL = 'leads@casevalue.law';
const FROM_NAME = 'CaseValue.law';

// CORS headers for cross-origin embed requests
const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Content-Type': 'application/json',
};

/**
 * Validate email format
 */
function isValidEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

/**
 * Escape HTML to prevent XSS in email body
 */
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Build professional HTML email template for lead notification
 */
function buildEmailHtml(lead) {
  const rows = [
    ['Name', `${escapeHtml(lead.first_name || '')} ${escapeHtml(lead.last_name || '')}`],
    ['Email', escapeHtml(lead.email || '')],
    ['Phone', escapeHtml(lead.phone || '')],
    ['Case Type', escapeHtml(lead.case_type || '')],
    ['State', escapeHtml(lead.state || '')],
    ['Language', escapeHtml(lead.language || 'en')],
    ['Source', lead.source === 'embed' ? 'Embedded Calculator' : 'CaseValue.law'],
  ];

  if (lead.embed_referrer && lead.embed_referrer !== 'unknown') {
    rows.push(['Referrer', escapeHtml(lead.embed_referrer)]);
  }
  if (lead.partner_id) {
    rows.push(['Partner ID', escapeHtml(lead.partner_id)]);
  }

  const tableRows = rows
    .map(([label, value]) =>
      `<tr><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:600;color:#374151;width:140px">${label}</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;color:#111827">${value}</td></tr>`
    )
    .join('');

  const summarySection = lead.questionnaire_summary
    ? `<div style="margin-top:24px;padding:16px;background:#f9fafb;border-radius:8px;border:1px solid #e5e7eb">
        <h3 style="margin:0 0 12px;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em">Case Details</h3>
        <pre style="margin:0;white-space:pre-wrap;font-family:inherit;font-size:14px;color:#374151;line-height:1.6">${escapeHtml(lead.questionnaire_summary)}</pre>
      </div>`
    : '';

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f3f4f6">
  <div style="max-width:600px;margin:0 auto;padding:24px">
    <div style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)">
      <!-- Header -->
      <div style="background:linear-gradient(135deg,#1e293b,#334155);padding:24px 32px">
        <h1 style="margin:0;color:#fbbf24;font-size:20px;font-weight:700">New Lead from CaseValue.law</h1>
        <p style="margin:6px 0 0;color:#94a3b8;font-size:14px">${escapeHtml(lead.case_type || 'Case')} inquiry from ${escapeHtml(lead.state || 'unknown state')}</p>
      </div>
      <!-- Body -->
      <div style="padding:24px 32px">
        <table style="width:100%;border-collapse:collapse;font-size:14px">
          ${tableRows}
        </table>
        ${summarySection}
      </div>
      <!-- Footer -->
      <div style="padding:16px 32px;background:#f9fafb;border-top:1px solid #e5e7eb">
        <p style="margin:0;font-size:12px;color:#9ca3af;text-align:center">
          This lead was generated by <a href="https://casevalue.law" style="color:#3b82f6;text-decoration:none">CaseValue.law</a> — Free Legal Case Value Calculator
        </p>
      </div>
    </div>
  </div>
</body>
</html>`;
}

exports.handler = async (event) => {
  // Handle preflight
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: CORS_HEADERS, body: '' };
  }

  // Only accept POST
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Method Not Allowed' }) };
  }

  try {
    const body = JSON.parse(event.body || '{}');

    // Validate required fields
    if (!body.first_name) {
      return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Missing first_name' }) };
    }
    if (!body.email || !isValidEmail(body.email)) {
      return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Invalid or missing email' }) };
    }

    // Log the lead regardless of email delivery
    console.log(JSON.stringify({
      type: 'lead_received',
      partner_id: body.partner_id || 'none',
      case_type: body.case_type || 'unknown',
      state: body.state || 'unknown',
      has_intake_email: !!body.intake_email,
      timestamp: new Date().toISOString(),
    }));

    // If no intake email, log-only mode (no email sent)
    if (!body.intake_email || !isValidEmail(body.intake_email)) {
      return {
        statusCode: 200,
        headers: CORS_HEADERS,
        body: JSON.stringify({ ok: true, emailed: false, reason: 'no_intake_email' }),
      };
    }

    // Check for Resend API key
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      console.error('RESEND_API_KEY environment variable is not set');
      return {
        statusCode: 200,
        headers: CORS_HEADERS,
        body: JSON.stringify({ ok: true, emailed: false, reason: 'email_not_configured' }),
      };
    }

    // Build email
    const caseType = body.case_type || 'Case';
    const firstName = body.first_name || '';
    const lastName = body.last_name || '';
    const subject = `New Lead: ${caseType} - ${firstName} ${lastName} | CaseValue`.trim();

    const emailPayload = {
      from: `${FROM_NAME} <${FROM_EMAIL}>`,
      to: [body.intake_email],
      bcc: [BCC_EMAIL],
      reply_to: body.email,
      subject,
      html: buildEmailHtml(body),
    };

    // Send via Resend API
    const response = await fetch(RESEND_API_URL, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(emailPayload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Resend API error:', response.status, errorText);
      return {
        statusCode: 200,
        headers: CORS_HEADERS,
        body: JSON.stringify({ ok: true, emailed: false, reason: 'email_delivery_failed' }),
      };
    }

    const result = await response.json();
    console.log('Email sent successfully:', result.id);

    return {
      statusCode: 200,
      headers: CORS_HEADERS,
      body: JSON.stringify({ ok: true, emailed: true }),
    };
  } catch (err) {
    console.error('process-lead error:', err);
    return {
      statusCode: 400,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: 'Invalid request body' }),
    };
  }
};
